[package]
name = "evaluation_domains"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../zexe/algebra", features = [ "parallel", "bn_382", "asm" ] }
ff-fft = { path = "../../zexe/ff-fft" }
