[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", branch = "dlog-only-clean-cargo", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
ff-fft = { git = "https://github.com/o1-labs/zexe/", branch = "dlog-only-clean-cargo" }
rand = "0.7.3"
